name: Update gist with WakaTime stats
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: lengthmin/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 307bc0ddd41d93b883204a77187343fc
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
          YUQUE_NAMESPACE: artin/personal
          YUQUE_DOC_ID: 55766500
          TIMEZONE: Asia/Shanghai
          TZ: Asia/Shanghai
